<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
	<NoWarn>$(NoWarn);CA1416</NoWarn>
    <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
    <TargetFrameworks>net10.0-android</TargetFrameworks>
    <TargetFrameworks Condition="!$([MSBuild]::IsOSPlatform('linux'))">$(TargetFrameworks);net10.0-ios;net10.0-maccatalyst</TargetFrameworks>
    <TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net10.0-windows10.0.19041.0</TargetFrameworks>
    <!-- Note for MacCatalyst:
		The default runtime is maccatalyst-x64, except in Release config, in which case the default is maccatalyst-x64;maccatalyst-arm64.
		When specifying both architectures, use the plural <RuntimeIdentifiers> instead of the singular <RuntimeIdentifier>.
		The Mac App Store will NOT accept apps with ONLY maccatalyst-arm64 indicated;
		either BOTH runtimes must be indicated or ONLY macatalyst-x64. -->
    <!-- For example: <RuntimeIdentifiers>maccatalyst-x64;maccatalyst-arm64</RuntimeIdentifiers> -->
    <OutputType>Exe</OutputType>
    <RootNamespace>Krepim.Mobile</RootNamespace>
    <UseMaui>true</UseMaui>
    <SingleProject>true</SingleProject>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <!-- Enable XAML source generation for faster build times and improved performance.
		     This generates C# code from XAML at compile time instead of runtime inflation.
		     To disable, remove this line.
		     For individual files, you can override by setting Inflator metadata:
		       <MauiXaml Update="MyPage.xaml" Inflator="Default" /> (reverts to defaults: Runtime for Debug, XamlC for Release)
		       <MauiXaml Update="MyPage.xaml" Inflator="Runtime" /> (force runtime inflation) -->
    <MauiXamlInflator>SourceGen</MauiXamlInflator>
    <!-- Display name -->
    <ApplicationTitle>Krepim.Mobile</ApplicationTitle>
    <!-- App Identifier -->
    <ApplicationId>com.companyname.krepim.mobile</ApplicationId>
    <!-- Versions -->
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
    <ApplicationVersion>1</ApplicationVersion>
    <!-- To develop, package, and publish an app to the Microsoft Store, see: https://aka.ms/MauiTemplateUnpackaged -->
    <WindowsPackageType>None</WindowsPackageType>
    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">15.0</SupportedOSPlatformVersion>
    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">15.0</SupportedOSPlatformVersion>
    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
    <TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
  </PropertyGroup>
  <ItemGroup>
    <!-- App Icon -->
    <MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#512BD4" />
    <MauiImage Include="Resources\Images\Icons\Svg\home.svg" />
    <MauiImage Include="Resources\Images\Icons\Svg\location.svg" />
    <MauiImage Include="Resources\Images\Icons\Svg\profile.svg" />
    <MauiImage Include="Resources\Images\Icons\Svg\search.svg" />
    <MauiImage Include="Resources\Images\Partners\boltru.jpg" />
    <MauiImage Include="Resources\Images\Partners\metallservice.jpg" />
    <MauiImage Include="Resources\Images\Partners\mtk.jpg" />
    <MauiImage Include="Resources\Images\Partners\pic.jpg" />
    <MauiImage Include="Resources\Images\Partners\russconnect.jpg" />
    <MauiImage Include="Resources\Images\Partners\volzgskiy.jpg" />
    <MauiImage Include="Resources\Images\Partners\zitar.jpg" />
    <!-- Splash Screen -->
    <MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#512BD4" BaseSize="128,128" />
    <!-- Images -->
    <MauiImage Include="Resources\Images\*" />
    <MauiImage Update="Resources\Images\dotnet_bot.png" Resize="True" BaseSize="300,185" />
    <!-- Custom Fonts -->
    <MauiFont Include="Resources\Fonts\*" />
    <!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
    <MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>
  <ItemGroup>
    <AndroidResource Remove="Platforms\Android\Resources\xml\network_security_config.xml" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Resources\Images\Banners\banner_2.png" />
    <None Remove="Resources\Images\Icons\General\anchors_2.png" />
    <None Remove="Resources\Images\Icons\General\arma.png" />
    <None Remove="Resources\Images\Icons\General\bolts_2.png" />
    <None Remove="Resources\Images\Icons\General\clock_2.png" />
    <None Remove="Resources\Images\Icons\General\cons.png" />
    <None Remove="Resources\Images\Icons\General\dubel.png" />
    <None Remove="Resources\Images\Icons\General\fast_deliv.png" />
    <None Remove="Resources\Images\Icons\General\gaiki.png" />
    <None Remove="Resources\Images\Icons\General\geo.png" />
    <None Remove="Resources\Images\Icons\General\money_2.png" />
    <None Remove="Resources\Images\Icons\General\nails_2.png" />
    <None Remove="Resources\Images\Icons\General\price.png" />
    <None Remove="Resources\Images\Icons\General\selfr.png" />
    <None Remove="Resources\Images\Icons\General\shop.png" />
    <None Remove="Resources\Images\Icons\General\shur_samo.png" />
    <None Remove="Resources\Images\Icons\General\tools.png" />
    <None Remove="Resources\Images\Icons\General\tube.png" />
    <None Remove="Resources\Images\Icons\General\waranty.png" />
    <None Remove="Resources\Images\Icons\General\waranty_2.png" />
    <None Remove="Resources\Images\Icons\Other\analis.png" />
    <None Remove="Resources\Images\Icons\Other\box.png" />
    <None Remove="Resources\Images\Icons\Other\clock.png" />
    <None Remove="Resources\Images\Icons\Other\count.png" />
    <None Remove="Resources\Images\Icons\Other\def.png" />
    <None Remove="Resources\Images\Icons\Other\deliv.png" />
    <None Remove="Resources\Images\Icons\Other\info.png" />
    <None Remove="Resources\Images\Icons\Other\money.png" />
    <None Remove="Resources\Images\Icons\Other\order.png" />
    <None Remove="Resources\Images\Icons\Other\perc.png" />
    <None Remove="Resources\Images\Icons\Other\phone.png" />
    <None Remove="Resources\Images\Icons\Other\statistic.png" />
    <None Remove="Resources\Images\Icons\Other\warehouse.png" />
    <None Remove="Resources\Images\Icons\Products\anchor.png" />
    <None Remove="Resources\Images\Icons\Products\batt.png" />
    <None Remove="Resources\Images\Icons\Products\build.png" />
    <None Remove="Resources\Images\Icons\Products\deliv.png" />
    <None Remove="Resources\Images\Icons\Products\drel.png" />
    <None Remove="Resources\Images\Icons\Products\fittings.png" />
    <None Remove="Resources\Images\Icons\Products\level.png" />
    <None Remove="Resources\Images\Icons\Products\mbolts.png" />
    <None Remove="Resources\Images\Icons\Products\mcement.png" />
    <None Remove="Resources\Images\Icons\Products\nails.png" />
    <None Remove="Resources\Images\Icons\Products\perf.png" />
    <None Remove="Resources\Images\Icons\Products\product.png" />
    <None Remove="Resources\Images\Icons\Products\rivets.png" />
    <None Remove="Resources\Images\Icons\Products\saw.png" />
    <None Remove="Resources\Images\Icons\Products\screws.png" />
    <None Remove="Resources\Images\Icons\Products\step.png" />
    <None Remove="Resources\Images\Icons\Products\wall.png" />
    <None Remove="Resources\Images\Icons\Svg\basket.svg" />
    <None Remove="Resources\Images\Icons\Svg\catalog.svg" />
    <None Remove="Resources\Images\Icons\Svg\home.svg" />
    <None Remove="Resources\Images\Icons\Svg\location.svg" />
    <None Remove="Resources\Images\Icons\Svg\main.svg" />
    <None Remove="Resources\Images\Icons\Svg\profile.svg" />
    <None Remove="Resources\Images\Icons\Svg\search.svg" />
    <None Remove="Resources\Images\Icons\Svg\worker.svg" />
    <None Remove="Resources\Images\Partners\boltru-130x100.jpg" />
    <None Remove="Resources\Images\Partners\boltru.jpg" />
    <None Remove="Resources\Images\Partners\metallservice-130x100.jpg" />
    <None Remove="Resources\Images\Partners\metallservice.jpg" />
    <None Remove="Resources\Images\Partners\mtk-130x100.jpg" />
    <None Remove="Resources\Images\Partners\mtk.jpg" />
    <None Remove="Resources\Images\Partners\ooo-pic-130x100.jpg" />
    <None Remove="Resources\Images\Partners\pic.jpg" />
    <None Remove="Resources\Images\Partners\russconnect-130x100.jpg" />
    <None Remove="Resources\Images\Partners\russconnect.jpg" />
    <None Remove="Resources\Images\Partners\volzgskiy-instrument-130x100.jpg" />
    <None Remove="Resources\Images\Partners\volzgskiy.jpg" />
    <None Remove="Resources\Images\Partners\zitar-130x100.jpg" />
    <None Remove="Resources\Images\Partners\zitar.jpg" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Maui" Version="14.2.0" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.10" />
    <PackageReference Include="Microsoft.Maui.Controls" Version="10.0.80" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.8" />
  </ItemGroup>
  <ItemGroup>
    <MauiXaml Update="Features\Auth\Views\LoginPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Features\Auth\Views\RegisterPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Features\Basket\Views\BasketPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Features\Catalog\Views\CatalogPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Features\Catalog\Views\ProductDetailPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Features\Home\Views\HomePage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Features\Ordering\Views\MyOrdersPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Features\Ordering\Views\OrderDetailPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Features\Ordering\Views\OrdersDashboardPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Features\Payment\Views\MockPayPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Features\Profile\Views\ChangePasswordPopup.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Features\Profile\Views\ProfilePage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
  </ItemGroup>
  <ItemGroup>
  	 <EmbeddedResource Include="appsettings.Development.json" />
  </ItemGroup>
  <ItemGroup>
    <MauiImage Include="Resources\Images\Banners\banner_2.png" />
    <MauiImage Include="Resources\Images\Icons\General\anchors_2.png" />
    <MauiImage Include="Resources\Images\Icons\General\arma.png" />
    <MauiImage Include="Resources\Images\Icons\General\bolts_2.png" />
    <MauiImage Include="Resources\Images\Icons\General\clock_2.png" />
    <MauiImage Include="Resources\Images\Icons\General\cons.png" />
    <MauiImage Include="Resources\Images\Icons\General\dubel.png" />
    <MauiImage Include="Resources\Images\Icons\General\fast_deliv.png" />
    <MauiImage Include="Resources\Images\Icons\General\gaiki.png" />
    <MauiImage Include="Resources\Images\Icons\General\geo.png" />
    <MauiImage Include="Resources\Images\Icons\General\money_2.png" />
    <MauiImage Include="Resources\Images\Icons\General\nails_2.png" />
    <MauiImage Include="Resources\Images\Icons\General\price.png" />
    <MauiImage Include="Resources\Images\Icons\General\selfr.png" />
    <MauiImage Include="Resources\Images\Icons\General\shop.png" />
    <MauiImage Include="Resources\Images\Icons\General\shur_samo.png" />
    <MauiImage Include="Resources\Images\Icons\General\tools.png" />
    <MauiImage Include="Resources\Images\Icons\General\tube.png" />
    <MauiImage Include="Resources\Images\Icons\General\waranty.png" />
    <MauiImage Include="Resources\Images\Icons\General\waranty_2.png" />
    <MauiImage Include="Resources\Images\Icons\Other\analis.png" />
    <MauiImage Include="Resources\Images\Icons\Other\box.png" />
    <MauiImage Include="Resources\Images\Icons\Other\clock.png" />
    <MauiImage Include="Resources\Images\Icons\Other\count.png" />
    <MauiImage Include="Resources\Images\Icons\Other\def.png" />
    <MauiImage Include="Resources\Images\Icons\Other\info.png" />
    <MauiImage Include="Resources\Images\Icons\Other\money.png" />
    <MauiImage Include="Resources\Images\Icons\Other\order.png" />
    <MauiImage Include="Resources\Images\Icons\Other\perc.png" />
    <MauiImage Include="Resources\Images\Icons\Other\phone.png" />
    <MauiImage Include="Resources\Images\Icons\Other\statistic.png" />
    <MauiImage Include="Resources\Images\Icons\Other\warehouse.png" />
    <MauiImage Include="Resources\Images\Icons\Products\anchor.png" />
    <MauiImage Include="Resources\Images\Icons\Products\batt.png" />
    <MauiImage Include="Resources\Images\Icons\Products\build.png" />
    <MauiImage Include="Resources\Images\Icons\Products\deliv.png" />
    <MauiImage Include="Resources\Images\Icons\Products\drel.png" />
    <MauiImage Include="Resources\Images\Icons\Products\fittings.png" />
    <MauiImage Include="Resources\Images\Icons\Products\level.png" />
    <MauiImage Include="Resources\Images\Icons\Products\mbolts.png" />
    <MauiImage Include="Resources\Images\Icons\Products\mcement.png" />
    <MauiImage Include="Resources\Images\Icons\Products\nails.png" />
    <MauiImage Include="Resources\Images\Icons\Products\perf.png" />
    <MauiImage Include="Resources\Images\Icons\Products\product.png" />
    <MauiImage Include="Resources\Images\Icons\Products\rivets.png" />
    <MauiImage Include="Resources\Images\Icons\Products\saw.png" />
    <MauiImage Include="Resources\Images\Icons\Products\screws.png" />
    <MauiImage Include="Resources\Images\Icons\Products\step.png" />
    <MauiImage Include="Resources\Images\Icons\Products\wall.png" />
    <MauiImage Include="Resources\Images\Icons\Svg\basket.svg" />
    <MauiImage Include="Resources\Images\Icons\Svg\catalog.svg" />
  </ItemGroup>
</Project>