<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
	<PackageReference Include="FluentAssertions" />
	<PackageReference Include="NSubstitute" />
	<PackageReference Include="Testcontainers" />
	<PackageReference Include="Testcontainers.PostgreSql" />
	<PackageReference Include="Testcontainers.RabbitMq" />
	<PackageReference Include="Testcontainers.Redis" />
	<PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" />
	<PackageReference Include="StackExchange.Redis" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\src\Services\Basket\Krepim.Basket.Api\Krepim.Basket.Api.csproj" />
    <ProjectReference Include="..\..\..\Shared\Krepim.Testing.Shared\Krepim.Testing.Shared.csproj" />
  </ItemGroup>
</Project>