<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
	<PackageReference Include="Aspire.MongoDB.Driver" />
	<InternalsVisibleTo Include="Krepim.Catalog.IntegrationTests" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\Krepim.SharedKernel\Krepim.SharedKernel.csproj" />
    <ProjectReference Include="..\Krepim.Catalog.Infrastructure\Krepim.Catalog.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\Aspire\Krepim.Aspire.ServiceDefaults\Krepim.Aspire.ServiceDefaults.csproj" />
  </ItemGroup>
</Project>