<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
		<PackageReference Include="Testcontainers.PostgreSql" />
		<PackageReference Include="Testcontainers.MongoDb" />
		<PackageReference Include="Testcontainers.RabbitMq" />
		<PackageReference Include="Testcontainers.Redis" />
		<PackageReference Include="FluentAssertions" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" />
		<PackageReference Include="xunit.runner.visualstudio">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="xunit.v3" />
		<PackageReference Include="xunit.v3.extensibility.core" />
	</ItemGroup>

</Project>
