<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\Krepim.EventBus\Krepim.EventBus.csproj" />
    <ProjectReference Include="..\Krepim.Catalog.Domain\Krepim.Catalog.Domain.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Krepim.SharedKernel\Krepim.SharedKernel.csproj" />
	<PackageReference Include="MassTransit" />
	<PackageReference Include="MassTransit.RabbitMQ" />
	<PackageReference Include="FluentValidation" />
	<PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
	<InternalsVisibleTo Include="Krepim.Catalog.Application.Tests" />
  </ItemGroup>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>